name: window_paint
description: WindowPaint lets you pan, zoom and paint over any other widget. It
  uses the new InteractiveViewer together with a CustomPainter, giving you the
  bare minimum to get you started.
version: 0.7.0
homepage: https://github.com/graknol/window_paint
repository: https://github.com/graknol/window_paint
issue_tracker: https://github.com/graknol/window_paint/issues

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  measurer: ^2.1.1
  uuid: ^4.5.0
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
